version: '3'

networks:
  simpleapp_network:
    driver: bridge

services:
  db:
    image: mongo:latest
    container_name: simpleapp_mongo
    expose:
      - "27017"
    networks:
      - simpleapp_network
    
  nginx:
    build: ./Infrastructure/nginx
    image: simpleapp_nginx
    container_name: simpleapp_nginx
    ports:
      - "80:80"
    networks:
      - simpleapp_network
    depends_on:
      - simpleapp_1
      - simpleapp_2
  
  redis:
    build: ./Infrastructure/redis
    image: simpleapp_redis
    container_name: simpleapp_redis
    expose:
      - "6379"
    networks:
      - simpleapp_network
    depends_on:
      - simpleapp_1
      - simpleapp_2
  
  simpleapp_1:
    build: ./AspNetCoreMvc
    image: simpleapp
    container_name: simpleapp_1
    expose:
      - "60000"
    depends_on:
      - db
    networks:
      - simpleapp_network
  
  simpleapp_2:
    image: simpleapp
    container_name: simpleapp_2
    expose:
      - "60000"
    depends_on:
      - db
    networks:
      - simpleapp_network